server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_jwt?useSSL=false
    username: root
    password: password
    initialization-mode: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: 'create-drop'

# App Properties
koko:
  app:
    jwtSecret: JwtSecretKey
    jwtExpirationMs: 86400000
