server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

# App Properties
koko:
  app:
    jwtSecret: JwtSecretKey
    jwtExpirationMs: 86400000
